document.documentElement.innerHTML = ''
document.title = 'AudibleHero!'
document.body.innerHTML = '<div id="app"><router-view></router-view></div>'
document.body.className = 'show'
document.documentElement.className = 'show'
