on:
  workflow_dispatch:

name: Build and publish

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - run: npm i

      - run: npm run prettier

      - run: npm run eslint

      - run: npm run test

      - run: npm run prod

      - run: node -p 'm="./ext/manifest.json";x=require(m);x.version=`${x.version+1}`;require("fs").writeFileSync(m,JSON.stringify(x,null,"  "))'

      - name: Set env
        run: |
          VER=$(node -p 'require("./ext/manifest.json").version')
          echo "Version $VER"
          echo "PKG_VERSION=$VER" >> $GITHUB_ENV

      - name: Git config
        run: |
          git config --global user.name 'Eirik Brandtzæg'
          git config --global user.email 'eirikb@eirikb.no'

      - run: git commit -am "Automatic update ${{ env.PKG_VERSION }}!" || true

      - run: git push

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.PKG_VERSION }}
          release_name: Release v${{ env.PKG_VERSION }}
          draft: false
          prerelease: false

      - uses: trmcnvn/chrome-addon@v2
        with:
          extension: hemgkbfmploojfhljdcpbloffgkfamlb
          zip: audiblehero.zip
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
